apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pulsar-pubsub
  namespace: {{ .Values.namespace }}
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: {{ .Values.pulsar.host | quote }}
  - name: token
    secretKeyRef:
      name: {{ .Values.pulsar.secretName }}
      key: {{ .Values.pulsar.tokenKey }}
  - name: enableBatching
    value: "true"
  - name: batchingMaxMessages
    value: "1000"