apiVersion: apps/v1
kind: Deployment
metadata:
  name: hammer-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hammer-producer
  template:
    metadata:
      labels:
        app: hammer-producer
    spec:
      initContainers:
        - name: wait-for-consumer
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z hammer-consumer-svc 50051; do echo waiting for consumer; sleep 2; done;']
      containers:
        - name: hammer
          image: {{ .Values.image | quote }}
          env:
            - name: MODE
              value: "producer"
            - name: PULSAR_URL
              value: {{ .Values.pulsar.url | quote }}
            - name: TOPIC_NAME
              value: {{ .Values.pulsar.topic | quote }}
            - name: PULSAR_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pulsar.tokenSecretName }}
                  key: token
          resources:
            {{- toYaml .Values.resources.producer | nindent 12 }}