replicaCount: 1
image: "om22shree/pulsar-hammer:v1"
mode: "consumer" # Options: producer, consumer
namespace: "pulsar"

pulsar:
  host: "pulsar-mini-proxy.pulsar.svc.cluster.local:6650"
  secretName: "pulsar-mini-token-admin" 
  tokenKey: "TOKEN"              

resources:
  limits:
    cpu: "4"
    memory: "2Gi"
  requests:
    cpu: "4"
    memory: "2Gi"