apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Release.Name | quote }}
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50051"
        # Gloo Ambient Mesh auto-detection
        istio.io/dataplane-mode: "ambient"
    spec:
      containers:
      - name: hammer
        image: {{ .Values.image }}
        env:
        - name: MODE
          value: {{ .Values.mode | quote }}
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"